from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s=Service('C:/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get("https://qahacking.guru/")
time.sleep(2)
driver.get("https://qahacking.guru/")
driver.set_window_size(1345, 728)
driver.find_element(By.XPATH, "/html/body/div/div[2]/div[1]/div/div/nav/div[2]/ul/li[3]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div/div[2]/div[1]/div/div/nav/div[2]/ul/li[3]/a").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".buttons:nth-child(8) > .btn-success").click()
time.sleep(2)
driver.find_element(By.NAME, "quantity[0]").clear()
driver.find_element(By.NAME, "quantity[0]").send_keys("167")
driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
driver.find_element(By.ID, "f_name").click()
driver.find_element(By.ID, "f_name").send_keys("Нюра")
time.sleep(2)
driver.find_element(By.ID, "l_name").send_keys("Бабкина")
time.sleep(2)
driver.find_element(By.ID, "email").send_keys("babnura@mail.ru")
time.sleep(2)
driver.find_element(By.ID, "street").send_keys("Ул.Белки Стрелки")
time.sleep(2)
driver.find_element(By.ID, "zip").send_keys("51900")
driver.find_element(By.ID, "city").send_keys("Орёл")
time.sleep(2)
driver.find_element(By.ID, "state").send_keys("Орловская")
time.sleep(2)
driver.find_element(By.XPATH, '//*[@id="country"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//*[@id="country"]').click()
driver.find_element(By.XPATH, '//*[@id="country"]/option[177]').click()
time.sleep(2)
driver.find_element(By.ID, "phone").click()
driver.find_element(By.ID, "phone").send_keys("+79285679034")
time.sleep(2)
driver.find_element(By.NAME, "next").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".name:nth-child(3) b").click()
time.sleep(2)
driver.find_element(By.ID, "payment_submit").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".name:nth-child(2) b").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".button").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".row_agb").click()
time.sleep(2)
driver.find_element(By.ID, "agb").click()
time.sleep(2)
driver.find_element(By.NAME, "finish_registration").click()