from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s=Service('C:/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.set_window_size(1345, 728)
driver.get("https://elementy.ru/")
driver.find_element(By.ID, "pgbody").click()
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="rmenu"]/a[1]/span[1]').click()
driver.find_element(By.NAME, 'words').send_keys("3,14")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="rmenu"]/div/div/form/input[2]').click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("3.14")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("Привет")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("???")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("$$$")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("ПрИвЕт")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("Слово")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").clear()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div/form/div[1]/span/input").send_keys("Слова")
time.sleep(1)
driver.find_element(By.XPATH, '//*[@id="search_form"]/div[2]/span').click()
driver.find_element(By.XPATH, "/html/body/div[2]/div[4]/div[2]/div[2]/div[1]/div[1]/form/input").click()
time.sleep(3)